<?php
/**
 * The admin-specific functionality of the plugin.
 *
 * @link       https://profiles.wordpress.org/nishatbd31/
 * @since      1.0.0
 *
 * @package    Autocomplete_Google_Address
 * @subpackage Autocomplete_Google_Address/admin
 */

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Autocomplete_Google_Address
 * @subpackage Autocomplete_Google_Address/admin
 * @author     Md Nishath Khandakar <https://profiles.wordpress.org/nishatbd31/>
 */
class AGA_Admin {

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param      string    $plugin_name       The name of this plugin.
	 * @param      string    $version    The version of this plugin.
	 */
	public function __construct( $plugin_name, $version ) {

		$this->plugin_name = $plugin_name;
		$this->version = $version;

	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles() {
        $screen = get_current_screen();
        if ( ! $screen || 'aga_form' !== $screen->post_type ) {
            return;
        }

		wp_enqueue_style( $this->plugin_name, AGA_PLUGIN_URL . 'admin/css/admin.css', array(), $this->version, 'all' );
        wp_enqueue_style( 'select2', 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css' );

	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {
        $screen = get_current_screen();
        if ( ! $screen || 'aga_form' !== $screen->post_type ) {
            return;
        }

		wp_enqueue_script( $this->plugin_name, AGA_PLUGIN_URL . 'admin/js/admin.js', array( 'jquery', 'select2' ), $this->version, false );
        wp_enqueue_script( 'select2', 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js', array( 'jquery' ), null, true );
        
        // Localize script data for admin.js
        wp_localize_script( $this->plugin_name, 'aga_admin_data', array(
            'ajax_url' => admin_url( 'admin-ajax.php' ),
            'nonce'    => wp_create_nonce( 'aga_admin_nonce' ),
        ) );
	}
    
        public function add_admin_menu() {
            // The Custom Post Type itself creates the top-level menu due to show_in_menu => true.
            // We only need to add the sub-menus now.
    
            // 'All Configurations' submenu is automatically generated by WordPress for the CPT,
            // so we don't need to add it manually here.
    
            // Add 'Add New' submenu.
;
    
            // Add 'Settings' submenu.
            add_submenu_page(
                'edit.php?post_type=aga_form', // Parent is the CPT's main menu slug
                __( 'Settings', 'autocomplete-google-address' ),
                __( 'Settings', 'autocomplete-google-address' ),
                'manage_options',
                'aga-settings',
                array( $this, 'render_settings_page' )
            );
    
            // Add 'Help' submenu.
            add_submenu_page(
                'edit.php?post_type=aga_form', // Parent is the CPT's main menu slug
                __( 'Help', 'autocomplete-google-address' ),
                __( 'Help', 'autocomplete-google-address' ),
                'manage_options',
                'aga-help',
                array( $this, 'render_help_page' )
            );
        }    
    /**
     * Renders the settings page view.
     *
     * @since 1.0.0
     */
    public function render_settings_page() {
        require_once AGA_PLUGIN_DIR . 'admin/views/html-admin-page-settings.php';
    }
    
    /**
     * Renders the help page view.
     *
     * @since 1.0.0
     */
    public function render_help_page() {
        require_once AGA_PLUGIN_DIR . 'admin/views/html-admin-page-help.php';
    }
}
